export const TRACKS = ['Tenure-line', 'Teaching', 'Research', 'Clinical', 'Academic staff', 'Emeritus'] as const;

export const INSTITUTION_TYPES = [
  'University',
  'Public research institute',
  'Independent nonprofit research institute',
] as const;

export const HONOR_CATEGORIES = [
  'academy',
  'fellow',
  'career_award',
  'major_award',
  'distinguished_professorship',
] as const;

export const REQUIRED_ROSTER_STRINGS = [
  'id',
  'name',
  'profileUrl',
  'lastUpdatedAt',
  'university',
  'city',
  'department',
] as const;

export const ROSTER_FIELDS = [
  ...REQUIRED_ROSTER_STRINGS,
  'institutionType',
  'websiteUrl',
  'scholarUrl',
  'linkedinUrl',
  'state',
  'country',
  'rank',
  'track',
  'vietnameseName',
  'researchAreas',
  'honors',
  'portrait',
  'portraitSource',
  'postdocInstitution',
  'postdocYear',
  'phdInstitution',
  'phdYear',
  'phdMajor',
  'mdInstitution',
  'mdYear',
  'msInstitution',
  'msYear',
  'msMajor',
  'undergradInstitution',
  'undergradYear',
  'undergradMajor',
  'otherDegrees',
] as const;

export const HONOR_FIELDS = ['name', 'organization', 'category', 'year', 'source'] as const;
export const OTHER_DEGREE_FIELDS = ['degree', 'institution', 'year', 'major', 'source'] as const;

export const UTC_TIMESTAMP_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;

export const LOCATIONS: string[] = [
  'US',
  'North America',
  'South America',
  'Africa',
  'Asia',
  'Australasia',
  'Europe',
  'World',
];

export const COUNTRY_TO_CONTINENT: Record<string, string> = {
  // North America
  'United States': 'North America',
  'US': 'North America',
  'USA': 'North America',
  'Canada': 'North America',
  'Mexico': 'North America',

  // South America
  'Brazil': 'South America',
  'Argentina': 'South America',
  'Chile': 'South America',
  'Colombia': 'South America',
  'Peru': 'South America',

  // Europe
  'United Kingdom': 'Europe',
  'UK': 'Europe',
  'Great Britain': 'Europe',
  'France': 'Europe',
  'Germany': 'Europe',
  'Switzerland': 'Europe',
  'Netherlands': 'Europe',
  'Belgium': 'Europe',
  'Sweden': 'Europe',
  'Norway': 'Europe',
  'Denmark': 'Europe',
  'Finland': 'Europe',
  'Italy': 'Europe',
  'Spain': 'Europe',
  'Austria': 'Europe',
  'Ireland': 'Europe',
  'Poland': 'Europe',
  'Czech Republic': 'Europe',
  'Portugal': 'Europe',
  'Greece': 'Europe',
  'Hungary': 'Europe',
  'Estonia': 'Europe',
  'Luxembourg': 'Europe',
  'Iceland': 'Europe',

  // Asia
  'Singapore': 'Asia',
  'Vietnam': 'Asia',
  'Hong Kong': 'Asia',
  'Japan': 'Asia',
  'South Korea': 'Asia',
  'Korea': 'Asia',
  'Taiwan': 'Asia',
  'China': 'Asia',
  'India': 'Asia',
  'Israel': 'Asia',
  'Saudi Arabia': 'Asia',
  'United Arab Emirates': 'Asia',
  'UAE': 'Asia',
  'Qatar': 'Asia',
  'Thailand': 'Asia',
  'Malaysia': 'Asia',
  'Philippines': 'Asia',
  'Indonesia': 'Asia',

  // Australasia
  'Australia': 'Australasia',
  'New Zealand': 'Australasia',

  // Africa
  'South Africa': 'Africa',
  'Egypt': 'Africa',
  'Nigeria': 'Africa',
  'Kenya': 'Africa',
  'Morocco': 'Africa',
};

export const COUNTRY_FLAGS: Record<string, string> = {
  'United States': '🇺🇸',
  'US': '🇺🇸',
  'USA': '🇺🇸',
  'Canada': '🇨🇦',
  'United Kingdom': '🇬🇧',
  'UK': '🇬🇧',
  'Australia': '🇦🇺',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Netherlands': '🇳🇱',
  'Switzerland': '🇨🇭',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Belgium': '🇧🇪',
  'Poland': '🇵🇱',
  'Ireland': '🇮🇪',
  'Singapore': '🇸🇬',
  'Vietnam': '🇻🇳',
  'Japan': '🇯🇵',
  'Hong Kong': '🇭🇰',
  'New Zealand': '🇳🇿',
  'South Korea': '🇰🇷',
  'Korea': '🇰🇷',
  'Taiwan': '🇹🇼',
  'China': '🇨🇳',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Austria': '🇦🇹',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Portugal': '🇵🇹',
  'Israel': '🇮🇱',
  'Saudi Arabia': '🇸🇦',
  'United Arab Emirates': '🇦🇪',
  'UAE': '🇦🇪',
  'Qatar': '🇶🇦',
  'India': '🇮🇳',
  'Thailand': '🇹🇭',
  'Malaysia': '🇲🇾',
  'Philippines': '🇵🇭',
  'Indonesia': '🇮🇩',
  'South Africa': '🇿🇦',
  'Egypt': '🇪🇬',
  'Nigeria': '🇳🇬',
  'Kenya': '🇰🇪',
  'Morocco': '🇲🇦',
  'Brazil': '🇧🇷',
  'Mexico': '🇲🇽',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
};

export const LOCATION_LABELS: Record<string, string> = {
  'US': '🇺🇸 United States',
  'North America': '🌎 North America',
  'South America': '🌎 South America',
  'Europe': '🌍 Europe',
  'Australasia': '🌏 Australasia',
  'Asia': '🌏 Asia',
  'Africa': '🌍 Africa',
  'World': '🌐 World',
};

export const ACADEMIC_FORTUNES = [
  '“The paper is accepted subject to minor revisions: please rewrite sections 1 through 7.” — Reviewer 2',
  '“In theory, theory and practice are the same. In academia, they are not.”',
  '“A PhD is about learning more and more about less and less until you know everything about nothing.”',
  'Reviewer 2 has entered the chat: “The authors failed to cite my 1998 workshop paper.”',
  'May your code compile on the first try and your deadline be Anywhere on Earth (AoE).',
  '“Grant proposals: the art of asking for funding to do what you have already completed.”',
  '“Publish or perish. Or publish and perish anyway.”',
  '“To steal ideas from one person is plagiarism; to steal from many is research.” — Wilson Mizner',
  'The three most dangerous things in academia: an assistant professor with an idea, an associate professor with a committee, and a full professor with time.',
  '“The best dissertation is a finished dissertation.”',
  'Reviewer 1: “A brilliant, transformative contribution!” Reviewer 2: “Reject. Fundamentally flawed and unreadable.”',
  '“I have discovered a truly remarkable proof of this theorem which this margin is too small to contain.” — Pierre de Fermat',
  'Correlation does not imply causation, but it does waggle its eyebrows and gesture suggestively.',
  'Academic career stages: 1. I know nothing. 2. I know everything. 3. Everyone knows nothing.',
  'Coffee converts into theorems, but only with appropriate peer review.',
  'Your paper has been sent to three reviewers. Two will never respond; the third will ask for experiments requiring a particle accelerator.',
  '“If we knew what it was we were doing, it would not be called research, would it?” — Albert Einstein',
  'Tenure: the state of being able to speak your mind without fear of losing your parking space.',
  'The conference deadline was extended by one week. You now have six more days to procrastinate before staying up all night.',
  'Hypothesis: An educated guess that usually turns out to be wrong in the most interesting possible way.',
  'LaTeX Warning: Citation “needed” on page 42 undefined on input line 314.',
  'Never let your advisor know how fast you can actually finish a task.',
  'Research is 10% inspiration, 20% perspiration, and 70% dealing with formatting guidelines.',
  'Behind every successful professor is a mountain of rejected grant proposals.',
  '“Academic politics are so vicious precisely because the stakes are so small.” — Wallace Sayre',
  'Congratulations! Your manuscript has been accepted with zero revisions! ...said no editor in human history.',
  'Future work: what we promised in the conclusion to distract from what didn’t work in the results.',
  'Teaching evaluations: “Professor was brilliant, explained everything clearly. 2/5 stars.”',
  'A department seminar is an event where one person speaks and forty professors check their email.',
  'May your funding be continuous, your citations rising, and your sabbatical uninterrupted.',
  '“Data! Data! Data! I can’t make bricks without clay.” — Sherlock Holmes',
  'A day in the library can save you a month in the laboratory.',
  '“An expert is a person who has made all the mistakes that can be made in a very narrow field.” — Niels Bohr',
  'Nothing is ever truly finished in academia—only submitted.',
] as const;
